metricbeat-playbook.yml

---
  - name: installing and launching filebeat
    hosts: webservers
    become: true
    tasks:

    # Use command module
    - name: download filebeat .deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb sudo dpkg -i filebeat-7.6.1-amd64.deb

    # Use command module
    - name: install filebeat .deb
      command: dpkg -i filebeat-7.6.1-amd64.deb

    - name: copy over and drop in filebeat.yml
      copy:
        src: /etc/ansible/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable and Configure System Module
      command: filebeat modules enable system

    - name: setup filebeat
      command: filebeat setup

    - name: start Filebeat service
      command: service filebeat start
